{% set version = "0.1.0" %}

package:
  name: geoindex-rs
  version: {{ version }}

source:
  url: https://github.com/kylebarron/geo-index/archive/refs/tags/py-v{{ version }}.tar.gz
  sha256: 11d8fae033748c142b68e184552dfe7e7a74efdd7a4fe9d3e4d9593eff92665c

build:
  script:
    - {{ PYTHON }} -m pip install ./python -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - geoindex_rs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kylebarron/geo-index
  summary: Fast, memory-efficient 2D spatial indexes for Python.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE_MIT
    - THIRDPARTY.yml
  license_url: https://github.com/kylebarron/geo-index/blob/main/LICENSE_MIT
  doc_url: https://github.com/kylebarron/geo-index/tree/main/python
  dev_url: https://github.com/kylebarron/geo-index

extra:
  recipe-maintainers:
    - kylebarron
